networks:
  homebox-network:
    external: true
  traefik-network:
    external: true

volumes:
  homebox-data:
  traefik-certificates:

services:
  homebox:
    image: ${HOMEBOX_IMAGE_TAG}
    volumes:
      - homebox-data:/data/
    environment:
      HBOX_OPTIONS_ALLOW_REGISTRATION: ${HBOX_OPTIONS_ALLOW_REGISTRATION}
      HBOX_OPTIONS_AUTO_INCREMENT_ASSET_ID: ${HBOX_OPTIONS_AUTO_INCREMENT_ASSET_ID}
      HBOX_LOG_LEVEL: ${HOMEBOX_LOG_LEVEL}
      HBOX_LOG_FORMAT: ${HOMEBOX_LOG_FORMAT}
      HBOX_WEB_MAX_UPLOAD_SIZE: ${HOMEBOX_WEB_MAX_UPLOAD_SIZE}
      HBOX_MAILER_HOST: ${HOMEBOX_SMTP_ADDRESS}
      HBOX_MAILER_PORT: ${HOMEBOX_SMTP_PORT}
      HBOX_MAILER_USERNAME: ${HOMEBOX_SMTP_USER_NAME}
      HBOX_MAILER_PASSWORD: ${HOMEBOX_SMTP_PASSWORD}
      HBOX_MAILER_FROM: ${HOMEBOX_EMAIL_FROM}
    networks:
      - homebox-network
      - traefik-network
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      # Match incoming requests on a specific hostname
      - "traefik.http.routers.homebox.rule=Host(`${HOMEBOX_HOSTNAME}`)"
      # Assign the router to a named Traefik service
      - "traefik.http.routers.homebox.service=homebox"
      # Use the 'websecure' (HTTPS) entry point
      - "traefik.http.routers.homebox.entrypoints=websecure"
      # Define the internal container port for routing
      - "traefik.http.services.homebox.loadbalancer.server.port=7745"
      # Enable TLS on this router
      - "traefik.http.routers.homebox.tls=true"
      # Use Let's Encrypt for certificate management
      - "traefik.http.routers.homebox.tls.certresolver=letsencrypt"
      # Pass the original Host header to the container
      - "traefik.http.services.homebox.loadbalancer.passhostheader=true"
      # Apply a compression middleware
      - "traefik.http.routers.homebox.middlewares=compresstraefik"
      # Define settings for the compression middleware
      - "traefik.http.middlewares.compresstraefik.compress=true"
      # Specify which Docker network Traefik should use for routing
      - "traefik.docker.network=traefik-network"
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_healthy

  traefik:
    image: ${TRAEFIK_IMAGE_TAG}
    command:
      # Set the log level (DEBUG, INFO, WARN, ERROR)
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      # Enable the built-in API and web-based dashboard on /dashboard
      - "--api.dashboard=true"
      # Enable the /ping endpoint so we can health-check Traefik
      - "--ping=true"
      # Assign the /ping endpoint to a dedicated entry point on port 8082
      - "--ping.entrypoint=ping"
      - "--entrypoints.ping.address=:8082"
      # Define the primary HTTP entry point on port 80
      - "--entrypoints.web.address=:80"
      # Define the secure (HTTPS) entry point on port 443
      - "--entrypoints.websecure.address=:443"
      # Enable the Docker provider to detect containers and their labels
      - "--providers.docker=true"
      # Point Traefik to the Docker socket
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # Prevent automatic exposure of all containers; only expose containers
      # with "traefik.enable=true"
      - "--providers.docker.exposedbydefault=false"
      # Use ACME (Let's Encrypt) to generate/renew certificates via TLS challenge
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # The email address used by Let's Encrypt for renewal notices
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      # The file where ACME certificates are stored inside the container
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      # Enable Prometheus metrics
      - "--metrics.prometheus=true"
      # Configure Prometheus histogram buckets
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      # Check for newer Traefik versions and optionally log that info
      - "--global.checknewversion=true"
      # Disable sending anonymous usage data to the Traefik maintainers
      - "--global.sendanonymoususage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/etc/traefik/acme
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping","--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      # Enable Traefik for this container.
      - "traefik.enable=true"
      # A router to expose the Traefik dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      # asic Authentication for the Traefik dashboard
      - "traefik.http.routers.dashboard.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      # Specify the internal server port to the dashboard service
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      # Pass the original Host header to the backend
      - "traefik.http.services.dashboard.loadbalancer.passhostheader=true"
      # HTTP -> HTTPS redirect for all hosts
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped
